version: '3.1'

services:

  server:
    build: ./stats/server
    image: stats-server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  stats-db:
    image: postgres:16.1-alpine
    container_name:
      "stats_db"
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user_stats
      - POSTGRES_PASSWORD=password

  main-service:
    build: ./main-service/
    image: main-service
    container_name: main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - server
    environment:

      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SERVICES_STATSSERVICE_URI=http://server:9090

  main-db:
    image: postgres:16.1-alpine
    container_name:
      "main_service_db"
    ports:
      - "4642:5432"
    environment:
      - POSTGRES_DB=main_service
      - POSTGRES_USER=user_main
      - POSTGRES_PASSWORD=password