version: '3.1'

services:

  stats-server:
    build: ./stats/server
    image: stats-server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db


  stats-db:
    image: postgres:16.1-alpine
    container_name:
      "stats_db_container"
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user_stats
      - POSTGRES_PASSWORD=password

  main-service:
    build: main-service
    image: main-service
    container_name: main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - main-service-db
    environment:
      - EXPLOREWITHME_main_service_URL=http://server:8080

  main-service-db:
    image: postgres:16.1-alpine
    container_name:
      "main_service_db_container"
    ports:
      - "4642:5432"
    environment:
      - POSTGRES_DB=main_service
      - POSTGRES_USER=user_main
      - POSTGRES_PASSWORD=password