version: '3.1'
services:
  stats-server:
    build: ./stats/server
    image: stats-server
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - EXPLOREWITHME_STATS_SERVER_URL=http://server:9090


  stats-db:
    image: postgres:16.1-alpine
    container_name:
      "stats-db_container"
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=user_stats
      - POSTGRES_PASSWORD=password
